export const FORTIS_LICENSE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAofAlIbKuAJOrnVPzsZGKUDJtWNyQB300II7M6ERvZO0=
-----END PUBLIC KEY-----`

export const FORTIS_LICENSE_PUBLIC_KEY_NOTE =
    'Development ed25519 public key. Replace with your production public key generated by scripts/license-keygen.mjs before shipping. Keep the matching private key offline.'
